spring.application.name=${APPLICATION_NAME}
server.port=${SERVER_PORT}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO}
spring.jpa.show-sql=${SHOW_SQL}
spring.jpa.database-platform=${DB_PLATFORM}

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

jwt.super.secret.key=${JWT_SUPER_SECRET_KEY}





