
spring.application.name=${APPLICATION_NAME}
server.port=${SERVER_PORT}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_NAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

spring.jpa.hibernate.ddl-auto=${DDL_AUTO}
spring.jpa.show-sql=${SHOW_SQL}
spring.jpa.database-platform=${DB_PLATFORM}

gemini.api.key=${GEMINI_API_KEY}
phi4.api.key=${Phi4_API_KEY}

jwt.super.secret.key=${JWT_SUPER_SECRET_KEY}

eureka.client.register-with-eureka=${REGISTER_WITH_EUREKA}
eureka.client.fetch-registry=${FETCH_REGISTRY}
eureka.client.service-url-defaultZone=${EUREKA_SERVER_URL}
