spring.application.name=${APPLICATION_NAME:auth-service}
server.port=${SERVER_PORT:8081}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/skill_route}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:8872}
spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.database-platform=${DB_PLATFORM:org.hibernate.dialect.MySQLDialect}

eureka.client.register-with-eureka=${REGISTER_WITH_EUREKA:true}
eureka.client.fetch-registry=${FETCH_REGISTRY:true}
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

jwt.super.secret.key=${JWT_SUPER_SECRET_KEY}
