spring.application.name=${APPLICATION_NAME}

server.port=${SERVER_PORT}

eureka.client.register-with-eureka=${REGISTER_WITH_EUREKA}
eureka.client.fetch-registry=${FETCH_REGISTRY}

eureka.client.service-url-defaultZone=${EUREKA_SERVER_URL}

jwt.super.secret.key=${JWT_SUPER_SECRET_KEY}


