spring.application.name=${APPLICATION_NAME}
server.port=${SERVER_PORT}

eureka.client.register-with-eureka=${REGISTER_WITH_EUREKA}
eureka.client.fetch-registry=${FETCH_REGISTRY}
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

gemini.api.key=${GEMINI_API_KEY}
jwt.super.secret.key=${JWT_SUPER_SECRET_KEY}